# This file was generated by GoReleaser. DO NOT EDIT.
cask "zz" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "51cdc22e9c8b76ea8d752191a67289e676223f0c5c3938a9e2ad5b7e25a6900a"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7c7047f4c3feaf3623fbab75182262d219854a5c7bcdd925633e88c37687715a"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "26a6383a6c0f2cba4a14f04860e1840b292660ba7c9d4bdd49e9d3c00bbec717"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "54ad5c54941458d95255b51c37042f032f248b176255c6bc53e369a705389298"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zz"
  desc "miniapps for the terminal"
  homepage "https://github.com/meleu/zzgo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zz"

  # No zap stanza required

end
