# This file was generated by GoReleaser. DO NOT EDIT.
cask "zzgo" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "377809d73e47327463300bac19c22c54e76dfc021072104f63a5ab9e836f4d4d"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "62cd3c65839767a7ce913488185cb3f36c41d450a94be955b848d09c12f74164"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ff4c409525ebac530de69e74a6a2344dfb5dc19ceadfab6c690291cd87724cf0"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bf3c10c96ca5b340d905e4544f7a6193e20daada88acc9471990fe147ff37f83"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zzgo"
  desc "miniapps for the terminal"
  homepage "https://github.com/meleu/zzgo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zz"

  # No zap stanza required

end
