# This file was generated by GoReleaser. DO NOT EDIT.
cask "zzgo" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "23fef7ef339123f027c836ee812dd22253d1708fadba88f0dea74a97e1944348"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ab741cd72a026c7c331aaaea2b0516b39b598e9cc80263ce59772d022f32ec7"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f373afb70fcd222b8205308c7f0a1300f22c86a90c21c1c31de7c28a213986a3"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1fc38bc3f5697a739fe6a80fdc41268f6b042dda1d4b56ac6faaf9880b9b9439"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zzgo"
  desc "miniapps for the terminal"
  homepage "https://github.com/meleu/zzgo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zzgo"

  # No zap stanza required

end
