# This file was generated by GoReleaser. DO NOT EDIT.
cask "zzgo" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "4d7d90f8405aa8d0d2900dc1b78edfe112bc412a454de58ef9b4466b5883fa21"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0120c199540f48824207a73eedabec1e69ae1d74e46f5470a542f92eed023d87"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "269b7649eb42e80b6a3e72d49b107e4567534006402f4d6807b3dcae119405f5"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "483d567dba239a1c3f100412267944765011524da18f8bc3889558d8394b1bdc"
      url "https://github.com/meleu/zzgo/releases/download/v#{version}/zzgo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zzgo"
  desc "miniapps for the terminal"
  homepage "https://github.com/meleu/zzgo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zzgo"

  # No zap stanza required

end
